<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;

class AclPermissionMap extends BaseConfig
{
    /**
     * Proyeccion runtime del mapa documentado en ACL_NOMENCLATURA_MAPA.md.
     *
     * Mantener este archivo alineado con el markdown para evitar duplicacion
     * de criterios entre documentacion, alias runtime y etiquetas visibles.
     *
     * @var array<string, array<int, string>>
     */
    public array $exactAliases = [
        'bypass_cliente_filter' => ['global_guard_cliente_bypass_ejecutar'],
        'bypass_tramite_tenant_access' => ['global_guard_tenant_tramite_bypass_ejecutar'],
        'override_puede_editar_modulo' => ['tramite_detalle_override_edicion_modulo_ejecutar'],
        'override_tramite_approved_lock' => ['tramite_detalle_override_aprobado_editar'],
        'override_tramite_status_28_readonly' => ['tramite_detalle_override_status_28_editar'],
        'sincronizar_tramites' => ['tramites_listado_sincronizacion_ejecutar'],
        'menu_notifications' => ['global_header_notifications_ver'],
        'header_buttons' => ['global_header_quick_actions_ver'],
        'ui_sidebar_cliente' => ['global_sidebar_cliente_ver'],
        'menu_dashboard_admin' => ['global_sidebar_menu_dashboard_admin_ver'],
        'menu_dashboard_cliente' => ['global_sidebar_menu_dashboard_cliente_ver'],
        'menu_tramites' => ['global_sidebar_menu_tramites_ver'],
        'menu_tramites_cliente' => ['global_sidebar_menu_tramites_cliente_ver'],
        'menu_tramites_tenencias' => ['global_sidebar_menu_tenencias_ver'],
        'menu_proceso_final' => ['global_sidebar_menu_proceso_final_ver'],
        'menu_clientes' => ['global_sidebar_menu_clientes_ver'],
        'menu_gestores' => ['global_sidebar_menu_gestores_ver'],
        'menu_documentos' => ['global_sidebar_menu_documentos_ver'],
        'menu_configuracion' => ['global_sidebar_menu_configuracion_ver'],
        'menu_permisos' => ['global_sidebar_menu_permisos_ver'],
        'menu_roles' => ['global_sidebar_menu_roles_ver'],
        'menu_monitoreo_actividad' => ['global_sidebar_menu_monitoreo_ver'],
        'menu_erp_sa' => ['global_sidebar_menu_erp_sa_ver'],
        'listar_tramite' => ['tramites_listado_tabla_listar'],
        'search_tramite' => ['tramites_listado_filtros_buscar'],
        'export_tramite' => ['tramites_listado_tabla_exportar'],
        'print_tramite' => ['tramites_listado_tabla_imprimir'],
        'read_tramite' => ['tramite_detalle_ver'],
        'create_tramite' => ['tramites_listado_boton_crear'],
        'clone_tramite' => ['tramites_listado_accion_clonar'],
        'editar_tramite' => ['tramite_detalle_formulario_editar'],
        'delete_tramite' => ['tramites_listado_accion_eliminar'],
        'editar_tramite_principal' => ['tramite_detalle_principal_formulario_editar'],
        'editar_tramite_asociado' => ['tramite_detalle_asociados_formulario_editar'],
        'delete_tramite_asociado' => ['tramite_detalle_asociados_registro_eliminar'],
        'section_inicial_datos' => ['paso_1_panel_datos_iniciales_ver'],
        'write_tramite_datos_tramite' => ['paso_1_formulario_editar'],
        'section_asigna_gestor' => ['paso_2_panel_asignacion_gestor_ver'],
        'tramite_view_gestor' => ['paso_2_resumen_gestor_ver'],
        'editar_gestores' => ['write_tramite_asigna_gestor'],
        'write_tramite_asigna_gestor' => ['paso_2_formulario_editar'],
        'section_pago_derechos' => ['paso_3_panel_pago_derechos_ver'],
        'section_linea_captura' => ['paso_3_panel_linea_captura_ver'],
        'section_documentos_pago' => ['paso_3_panel_documentos_pago_ver'],
        'editar_derechos' => ['write_tramite_pago_derechos'],
        'write_tramite_pago_derechos' => ['paso_3_formulario_editar'],
        'can_upload_dropzone_pago_derechos' => ['paso_3_dropzone_documentos_pago_subir'],
        'important_pasar_a_pagos' => ['paso_3_accion_autorizar'],
        'can_upload_dropzone_evidencias_finales' => ['paso_4_dropzone_evidencias_finales_subir'],
        'important_ir_pago_gestor' => ['paso_4_navegacion_ir_paso_5_ver'],
        'section_pago_gestor' => ['paso_5_panel_pago_gestor_ver'],
        'editar_pago_gestor' => ['paso_5_formulario_editar'],
        'can_upload_dropzone_pago_gestor' => ['paso_5_dropzone_pago_gestor_subir_legacy'],
        'can_upload_dropzone_pago_gestor_documentos' => ['paso_5_dropzone_documentos_pago_gestor_subir'],
        'important_ir_cobro_cliente' => ['paso_5_navegacion_ir_paso_6_ver'],
        'section_final_costos' => ['paso_6_panel_costos_finales_ver'],
        'list_cobro_cliente' => ['paso_6_tabla_cobro_cliente_listar'],
        'can_upload_dropzone_cobro_cliente' => ['paso_6_dropzone_cobro_cliente_subir'],
        'upload_cobro_cliente' => ['paso_6_dropzone_cobro_cliente_subir'],
        'important_cancelar_tramite' => ['paso_6_accion_cancelar'],
        'important_concluir_tramite' => ['paso_6_accion_concluir'],
        'listar_final_tramite' => ['tramites_finalizados_tabla_listar'],
        'listar_concluidos_tramite' => ['tramites_finalizados_tabla_listar'],
        'listar_tramites_concluidos' => ['tramites_finalizados_tabla_listar'],
        'read_final_tramite' => ['tramites_finalizados_detalle_ver'],
        'export_final_tramite' => ['tramites_finalizados_tabla_exportar'],
        'print_final_tramite' => ['tramites_finalizados_tabla_imprimir'],
        'clone_tramite_cancelado' => ['tramites_cancelados_accion_clonar'],
        'listar_tramites_cancelado' => ['tramites_cancelados_tabla_listar'],
        'read_tramite_cancelado' => ['tramites_cancelados_detalle_ver'],
        'editar_tramite_cancelado' => ['tramites_cancelados_formulario_editar'],
        'delete_tramite_cancelado' => ['tramites_cancelados_accion_eliminar'],
        'export_tramite_cancelado' => ['tramites_cancelados_tabla_exportar'],
        'print_tramite_cancelado' => ['tramites_cancelados_tabla_imprimir'],
        'quick_action_documentos' => ['tramite_detalle_quick_actions_documentos_ver'],
        'quick_action_documentos_add' => ['tramite_detalle_quick_actions_documentos_crear'],
        'quick_action_documentos_edit' => ['tramite_detalle_quick_actions_documentos_editar'],
        'quick_action_documentos_delete' => ['tramite_detalle_quick_actions_documentos_eliminar'],
        'quick_action_bitacora' => ['tramite_detalle_quick_actions_bitacora_ver'],
        'quick_action_bitacora_add' => ['tramite_detalle_quick_actions_bitacora_crear'],
        'quick_action_bitacora_edit' => ['tramite_detalle_quick_actions_bitacora_editar'],
        'quick_action_bitacora_delete' => ['tramite_detalle_quick_actions_bitacora_eliminar'],
        'quick_action_pagos_derecho' => ['tramite_detalle_quick_actions_pago_derechos_ver'],
        'quick_action_pagos_derecho_add' => ['tramite_detalle_quick_actions_pago_derechos_crear'],
        'quick_action_pagos_derecho_edit' => ['tramite_detalle_quick_actions_pago_derechos_editar'],
        'quick_action_pagos_derecho_delete' => ['tramite_detalle_quick_actions_pago_derechos_eliminar'],
        'quick_action_pago_gestor' => ['tramite_detalle_quick_actions_pago_gestor_ver'],
        'quick_action_pago_gestor_add' => ['tramite_detalle_quick_actions_pago_gestor_crear'],
        'quick_action_pago_gestor_edit' => ['tramite_detalle_quick_actions_pago_gestor_editar'],
        'quick_action_pago_gestor_delete' => ['tramite_detalle_quick_actions_pago_gestor_eliminar'],
        'quick_action_evidencias_finales' => ['tramite_detalle_quick_actions_evidencias_finales_ver'],
        'quick_action_evidencias_finales_add' => ['tramite_detalle_quick_actions_evidencias_finales_crear'],
        'quick_action_evidencias_finales_edit' => ['tramite_detalle_quick_actions_evidencias_finales_editar'],
        'quick_action_evidencias_finales_delete' => ['tramite_detalle_quick_actions_evidencias_finales_eliminar'],
        'quick_action_cobros_cliente' => ['tramite_detalle_quick_actions_cobro_cliente_ver'],
        'quick_action_cobros_cliente_add' => ['tramite_detalle_quick_actions_cobro_cliente_crear'],
        'quick_action_cobros_cliente_edit' => ['tramite_detalle_quick_actions_cobro_cliente_editar'],
        'quick_action_cobros_cliente_delete' => ['tramite_detalle_quick_actions_cobro_cliente_eliminar'],
        'monitoreo_auditoria_tramite' => ['monitoreo_auditoria_tabla_ver'],
        'monitoreo_bitacora_search' => ['monitoreo_bitacora_filtros_buscar'],
        'monitoreo_correccion_tramites' => ['monitoreo_correcciones_ver'],
        'wizard_list_only_own' => ['wizard_tramites_listado_propios_listar'],
        'tramitesn_filter_owner_only' => ['wizard_tramites_listado_propios_listar'],
        'mios_filter_status_11' => ['tramites_mios_filtro_status_11_filtrar'],
        'mios_filter_status_22' => ['tramites_mios_filtro_status_22_filtrar'],
        'editar_final' => ['tramites_finales_formulario_editar'],
        'eliminar_final' => ['tramites_finales_registro_eliminar'],
        'crear_final' => ['tramites_finales_registro_crear'],
        'listar_final' => ['tramites_finales_tabla_listar'],
        'final_autoriza_termino' => ['tramites_finales_accion_autorizar'],
        'tramite_pasa_a_final' => ['tramite_detalle_legacy_pasar_final_ejecutar'],
    ];

    /**
     * @var array<string, array<int, string>>
     */
    public array $splitAliases = [
        'listar_settings' => [
            'global_header_profile_menu_ver',
            'configuracion_catalogos_tabla_listar',
        ],
    ];

    /**
     * @var array<string, string>
     */
    public array $uiLabelOverrides = [
        'tramite_view_gestor' => 'Ver resumen de gestor',
        'editar_gestores' => 'Editar formulario de asignacion de gestor',
        'write_tramite_asigna_gestor' => 'Editar formulario de asignacion de gestor',
        'editar_derechos' => 'Editar formulario de pago de derechos',
        'write_tramite_pago_derechos' => 'Editar formulario de pago de derechos',
        'write_tramite_datos_tramite' => 'Editar formulario de datos del tramite',
        'can_upload_dropzone_pago_derechos' => 'Subir documentos de pago de derechos',
        'can_upload_dropzone_evidencias_finales' => 'Subir evidencias finales',
        'can_upload_dropzone_pago_gestor' => 'Subir archivos de pago a gestor',
        'can_upload_dropzone_pago_gestor_documentos' => 'Subir documentos de pago a gestor',
        'can_upload_dropzone_cobro_cliente' => 'Subir documentos de cobro a cliente',
        'upload_cobro_cliente' => 'Subir documentos de cobro a cliente',
        'important_pasar_a_pagos' => 'Autorizar paso 3 y pasar a pago a gestor',
        'important_ir_pago_gestor' => 'Ir a pago a gestor',
        'important_ir_cobro_cliente' => 'Ir a cobro a cliente',
        'important_cancelar_tramite' => 'Cancelar tramite',
        'important_concluir_tramite' => 'Concluir tramite',
        'section_inicial_datos' => 'Ver seccion de datos iniciales',
        'section_asigna_gestor' => 'Ver seccion de asignacion de gestor',
        'section_pago_derechos' => 'Ver seccion de pago de derechos',
        'section_linea_captura' => 'Ver seccion de linea de captura',
        'section_documentos_pago' => 'Ver seccion de documentos de pago',
        'section_pago_gestor' => 'Ver seccion de pago a gestor',
        'section_final_costos' => 'Ver seccion de costos finales',
        'list_cobro_cliente' => 'Listar cobros a cliente',
        'quick_action_documentos' => 'Ver acciones rapidas de documentos',
        'quick_action_bitacora' => 'Ver acciones rapidas de bitacora',
        'quick_action_pagos_derecho' => 'Ver acciones rapidas de pagos de derecho',
        'quick_action_pago_gestor' => 'Ver acciones rapidas de pago a gestor',
        'quick_action_evidencias_finales' => 'Ver acciones rapidas de evidencias finales',
        'quick_action_cobros_cliente' => 'Ver acciones rapidas de cobros a cliente',
        'editar_final' => 'Editar datos finales',
        'read_final_tramite' => 'Ver detalle de tramite final',
        'listar_final_tramite' => 'Listar tramites finales',
        'listar_tramites_concluidos' => 'Listar tramites concluidos',
        'listar_concluidos_tramite' => 'Listar tramites concluidos',
        'final_autoriza_termino' => 'Autorizar termino final',
    ];
}
