START TRANSACTION;

-- Step 1 de la migracion ACL invisible.
-- Crea permisos canonicos nuevos sin eliminar ni modificar permisos legacy.
-- Script idempotente: solo inserta permission_name que aun no existen.

INSERT INTO us_permissions (permission_name, description, created_at, updated_at, status)
SELECT seed.permission_name,
       CONCAT('ACL canonico: ', seed.permission_name),
       NOW(),
       NOW(),
       1
FROM (
    SELECT 'global_guard_cliente_bypass_ejecutar' AS permission_name
    UNION ALL SELECT 'global_guard_tenant_tramite_bypass_ejecutar'
    UNION ALL SELECT 'tramite_detalle_override_edicion_modulo_ejecutar'
    UNION ALL SELECT 'tramite_detalle_override_aprobado_editar'
    UNION ALL SELECT 'tramite_detalle_override_status_28_editar'
    UNION ALL SELECT 'tramites_listado_sincronizacion_ejecutar'
    UNION ALL SELECT 'global_header_notifications_ver'
    UNION ALL SELECT 'global_header_quick_actions_ver'
    UNION ALL SELECT 'global_header_profile_menu_ver'
    UNION ALL SELECT 'configuracion_catalogos_tabla_listar'
    UNION ALL SELECT 'global_sidebar_cliente_ver'
    UNION ALL SELECT 'global_sidebar_menu_dashboard_admin_ver'
    UNION ALL SELECT 'global_sidebar_menu_dashboard_cliente_ver'
    UNION ALL SELECT 'global_sidebar_menu_tramites_ver'
    UNION ALL SELECT 'global_sidebar_menu_tramites_cliente_ver'
    UNION ALL SELECT 'global_sidebar_menu_tenencias_ver'
    UNION ALL SELECT 'global_sidebar_menu_proceso_final_ver'
    UNION ALL SELECT 'global_sidebar_menu_clientes_ver'
    UNION ALL SELECT 'global_sidebar_menu_gestores_ver'
    UNION ALL SELECT 'global_sidebar_menu_documentos_ver'
    UNION ALL SELECT 'global_sidebar_menu_configuracion_ver'
    UNION ALL SELECT 'global_sidebar_menu_permisos_ver'
    UNION ALL SELECT 'global_sidebar_menu_roles_ver'
    UNION ALL SELECT 'global_sidebar_menu_monitoreo_ver'
    UNION ALL SELECT 'global_sidebar_menu_erp_sa_ver'
    UNION ALL SELECT 'tramites_listado_tabla_listar'
    UNION ALL SELECT 'tramites_listado_filtros_buscar'
    UNION ALL SELECT 'tramites_listado_tabla_exportar'
    UNION ALL SELECT 'tramites_listado_tabla_imprimir'
    UNION ALL SELECT 'tramite_detalle_ver'
    UNION ALL SELECT 'tramites_listado_boton_crear'
    UNION ALL SELECT 'tramites_listado_accion_clonar'
    UNION ALL SELECT 'tramite_detalle_formulario_editar'
    UNION ALL SELECT 'tramites_listado_accion_eliminar'
    UNION ALL SELECT 'tramite_detalle_principal_formulario_editar'
    UNION ALL SELECT 'tramite_detalle_asociados_formulario_editar'
    UNION ALL SELECT 'tramite_detalle_asociados_registro_eliminar'
    UNION ALL SELECT 'paso_1_panel_datos_iniciales_ver'
    UNION ALL SELECT 'paso_1_formulario_editar'
    UNION ALL SELECT 'paso_2_panel_asignacion_gestor_ver'
    UNION ALL SELECT 'paso_2_resumen_gestor_ver'
    UNION ALL SELECT 'paso_2_formulario_editar'
    UNION ALL SELECT 'paso_3_panel_pago_derechos_ver'
    UNION ALL SELECT 'paso_3_panel_linea_captura_ver'
    UNION ALL SELECT 'paso_3_panel_documentos_pago_ver'
    UNION ALL SELECT 'paso_3_formulario_editar'
    UNION ALL SELECT 'paso_3_dropzone_documentos_pago_subir'
    UNION ALL SELECT 'paso_3_accion_autorizar'
    UNION ALL SELECT 'paso_4_dropzone_evidencias_finales_subir'
    UNION ALL SELECT 'paso_4_navegacion_ir_paso_5_ver'
    UNION ALL SELECT 'paso_5_panel_pago_gestor_ver'
    UNION ALL SELECT 'paso_5_formulario_editar'
    UNION ALL SELECT 'paso_5_dropzone_pago_gestor_subir_legacy'
    UNION ALL SELECT 'paso_5_dropzone_documentos_pago_gestor_subir'
    UNION ALL SELECT 'paso_5_navegacion_ir_paso_6_ver'
    UNION ALL SELECT 'paso_6_panel_costos_finales_ver'
    UNION ALL SELECT 'paso_6_tabla_cobro_cliente_listar'
    UNION ALL SELECT 'paso_6_dropzone_cobro_cliente_subir'
    UNION ALL SELECT 'paso_6_accion_cancelar'
    UNION ALL SELECT 'paso_6_accion_concluir'
    UNION ALL SELECT 'tramites_finalizados_tabla_listar'
    UNION ALL SELECT 'tramites_finalizados_detalle_ver'
    UNION ALL SELECT 'tramites_finalizados_tabla_exportar'
    UNION ALL SELECT 'tramites_finalizados_tabla_imprimir'
    UNION ALL SELECT 'tramites_cancelados_accion_clonar'
    UNION ALL SELECT 'tramites_cancelados_tabla_listar'
    UNION ALL SELECT 'tramites_cancelados_detalle_ver'
    UNION ALL SELECT 'tramites_cancelados_formulario_editar'
    UNION ALL SELECT 'tramites_cancelados_accion_eliminar'
    UNION ALL SELECT 'tramites_cancelados_tabla_exportar'
    UNION ALL SELECT 'tramites_cancelados_tabla_imprimir'
    UNION ALL SELECT 'tramite_detalle_quick_actions_documentos_ver'
    UNION ALL SELECT 'tramite_detalle_quick_actions_documentos_crear'
    UNION ALL SELECT 'tramite_detalle_quick_actions_documentos_editar'
    UNION ALL SELECT 'tramite_detalle_quick_actions_documentos_eliminar'
    UNION ALL SELECT 'tramite_detalle_quick_actions_bitacora_ver'
    UNION ALL SELECT 'tramite_detalle_quick_actions_bitacora_crear'
    UNION ALL SELECT 'tramite_detalle_quick_actions_bitacora_editar'
    UNION ALL SELECT 'tramite_detalle_quick_actions_bitacora_eliminar'
    UNION ALL SELECT 'tramite_detalle_quick_actions_pago_derechos_ver'
    UNION ALL SELECT 'tramite_detalle_quick_actions_pago_derechos_crear'
    UNION ALL SELECT 'tramite_detalle_quick_actions_pago_derechos_editar'
    UNION ALL SELECT 'tramite_detalle_quick_actions_pago_derechos_eliminar'
    UNION ALL SELECT 'tramite_detalle_quick_actions_pago_gestor_ver'
    UNION ALL SELECT 'tramite_detalle_quick_actions_pago_gestor_crear'
    UNION ALL SELECT 'tramite_detalle_quick_actions_pago_gestor_editar'
    UNION ALL SELECT 'tramite_detalle_quick_actions_pago_gestor_eliminar'
    UNION ALL SELECT 'tramite_detalle_quick_actions_evidencias_finales_ver'
    UNION ALL SELECT 'tramite_detalle_quick_actions_evidencias_finales_crear'
    UNION ALL SELECT 'tramite_detalle_quick_actions_evidencias_finales_editar'
    UNION ALL SELECT 'tramite_detalle_quick_actions_evidencias_finales_eliminar'
    UNION ALL SELECT 'tramite_detalle_quick_actions_cobro_cliente_ver'
    UNION ALL SELECT 'tramite_detalle_quick_actions_cobro_cliente_crear'
    UNION ALL SELECT 'tramite_detalle_quick_actions_cobro_cliente_editar'
    UNION ALL SELECT 'tramite_detalle_quick_actions_cobro_cliente_eliminar'
    UNION ALL SELECT 'monitoreo_auditoria_tabla_ver'
    UNION ALL SELECT 'monitoreo_bitacora_filtros_buscar'
    UNION ALL SELECT 'monitoreo_correcciones_ver'
    UNION ALL SELECT 'wizard_tramites_listado_propios_listar'
    UNION ALL SELECT 'tramites_mios_filtro_status_11_filtrar'
    UNION ALL SELECT 'tramites_mios_filtro_status_22_filtrar'
    UNION ALL SELECT 'tramites_finales_formulario_editar'
    UNION ALL SELECT 'tramites_finales_registro_eliminar'
    UNION ALL SELECT 'tramites_finales_registro_crear'
    UNION ALL SELECT 'tramites_finales_tabla_listar'
    UNION ALL SELECT 'tramites_finales_accion_autorizar'
    UNION ALL SELECT 'tramite_detalle_legacy_pasar_final_ejecutar'
) AS seed
LEFT JOIN us_permissions existing ON existing.permission_name = seed.permission_name
WHERE existing.id IS NULL;

-- Verificacion rapida del bootstrap canonico.
SELECT COUNT(*) AS canonical_permissions_present
FROM us_permissions
WHERE description LIKE 'ACL canonico: %';

COMMIT;