<?php

namespace Tests\App\Commands;

use App\Commands\S3MigrateCheck;
use Aws\MockHandler;
use Aws\Result;
use Aws\S3\S3Client;
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\Filters\CITestStreamFilter;
use Config\FileStorage as FileStorageConfig;
use Config\Services;

/**
 * Property 7: Migration coverage before flip.
 *
 * Before switching FILE_STORAGE_DRIVER to `s3`, the operator runs
 * `s3:migrate-check`. The property under test:
 *
 *   For an arbitrary set of local files synced with `aws s3 sync` WITHOUT
 *   `--delete` into the target bucket, every local file has an S3 counterpart,
 *   i.e. drift = localCount - s3Count <= 0, and the command reports SUCCESS.
 *   Conversely, if the sync is incomplete (bucket missing some local files),
 *   the command reports a WARNING that includes the drift value, so the check
 *   catches incomplete coverage BEFORE the flag is flipped.
 *
 * **Validates: Requirements 8.3, 8.4, 8.5**
 *
 * Determinism: the S3 object count is supplied through the {@see S3MigrateCheck::setS3Client()}
 * seam using an AWS SDK MockHandler (no real AWS). The `aws s3 sync` WITHOUT
 * `--delete` is modelled as an additive copy: the simulated bucket contains at
 * least every local file (effective local count), plus possibly pre-existing
 * extra objects. Local files are seeded on a temp disk so the real
 * {@see S3MigrateCheck::countLocalFiles()} (including the `*.tmp` exclusion)
 * runs unchanged. Cases are generated by seeded PHPUnit data providers.
 */
final class S3MigrateCheckCoveragePropertyTest extends CIUnitTestCase
{
    /** @var resource */
    private $streamFilterStdout;

    /** @var resource */
    private $streamFilterStderr;

    /** @var list<string> Temp roots created during a test, removed in tearDown. */
    private array $tempRoots = [];

    protected function setUp(): void
    {
        parent::setUp();

        CITestStreamFilter::$buffer = '';
        $this->streamFilterStdout   = stream_filter_append(STDOUT, 'CITestStreamFilter');
        $this->streamFilterStderr   = stream_filter_append(STDERR, 'CITestStreamFilter');
    }

    protected function tearDown(): void
    {
        stream_filter_remove($this->streamFilterStdout);
        stream_filter_remove($this->streamFilterStderr);

        foreach ($this->tempRoots as $root) {
            $this->removeTree($root);
        }
        $this->tempRoots = [];

        parent::tearDown();
    }

    /**
     * Property 7 (coverage): after an additive `aws s3 sync` (no --delete),
     * every local file has an S3 counterpart, so drift <= 0 and the command
     * reports SUCCESS.
     *
     * **Validates: Requirements 8.3, 8.4**
     *
     * @dataProvider coverageBeforeFlipProvider
     *
     * @param list<string> $files      Relative local paths to seed on disk.
     * @param int          $extra      Pre-existing extra objects already in the bucket.
     */
    public function testEveryLocalFileHasAnS3CounterpartBeforeFlip(array $files, int $extra): void
    {
        $root          = $this->seedLocalRoot($files);
        $effectiveLocal = $this->effectiveLocalCount($files);

        // `aws s3 sync` WITHOUT --delete = additive copy: bucket holds at least
        // every local file, plus any pre-existing extras.
        $s3Count = $effectiveLocal + $extra;
        $drift   = $effectiveLocal - $s3Count;

        $command = $this->makeCommand($root, $s3Count);
        $exit    = $command->run([]);
        $buffer  = CITestStreamFilter::$buffer;

        // Drift must be <= 0 for full coverage (Req 8.3, 8.4).
        $this->assertLessThanOrEqual(
            0,
            $drift,
            'Additive sync must never leave a positive drift (missing S3 objects).'
        );

        $this->assertSame(
            EXIT_SUCCESS,
            $exit,
            'With drift <= 0 the migrate-check must report success before the flip.'
        );

        // The reported drift line reflects the true drift value (Req 8.3).
        $this->assertStringContainsString('Drift  : ' . $drift . ' (local - s3)', $buffer);

        if ($effectiveLocal === 0) {
            // Degenerate coverage: nothing to migrate (Req 8.9) — still drift <= 0.
            $this->assertStringContainsString('no hay archivos locales que migrar', $buffer);
        } else {
            // Success message: each local file has an S3 counterpart (Req 8.4).
            $this->assertStringContainsString('cada archivo local tiene su contraparte en S3', $buffer);
        }

        // A warning must NOT appear when coverage is complete.
        $this->assertStringNotContainsString('ADVERTENCIA', $buffer);
    }

    /**
     * Property 7 (incomplete coverage): if the sync is partial (bucket missing
     * some local files) the check catches it BEFORE the flip by reporting a
     * WARNING that includes the drift value.
     *
     * **Validates: Requirement 8.5**
     *
     * @dataProvider partialSyncProvider
     *
     * @param list<string> $files   Relative local paths to seed on disk.
     * @param int          $missing How many local files are absent from the bucket.
     */
    public function testPartialSyncReportsWarningWithDriftBeforeFlip(array $files, int $missing): void
    {
        $root           = $this->seedLocalRoot($files);
        $effectiveLocal = $this->effectiveLocalCount($files);

        // Guard the generated case: a meaningful partial sync needs a real gap.
        $this->assertGreaterThanOrEqual(1, $effectiveLocal);
        $this->assertGreaterThanOrEqual(1, $missing);
        $this->assertLessThanOrEqual($effectiveLocal, $missing);

        $s3Count = $effectiveLocal - $missing; // bucket missing `$missing` objects
        $drift   = $effectiveLocal - $s3Count; // == $missing, strictly positive

        $command = $this->makeCommand($root, $s3Count);
        $exit    = $command->run([]);
        $buffer  = CITestStreamFilter::$buffer;

        $this->assertSame($missing, $drift, 'Drift must equal the number of missing objects.');
        $this->assertGreaterThan(0, $drift);

        // Command still returns success exit code, but MUST warn with the drift
        // value so the operator re-runs the sync before flipping (Req 8.5).
        $this->assertSame(EXIT_SUCCESS, $exit);
        $this->assertStringContainsString('Drift  : ' . $drift . ' (local - s3)', $buffer);
        $this->assertStringContainsString('ADVERTENCIA: faltan ' . $drift . ' objeto(s) en S3', $buffer);
        $this->assertStringNotContainsString('cada archivo local tiene su contraparte en S3', $buffer);
    }

    // ── Data providers (seeded) ─────────────────────────────────────────────

    /**
     * Arbitrary local file sets fully synced (plus optional pre-existing extra
     * objects). Deterministic across runs via per-case seeds.
     *
     * @return iterable<string, array{0: list<string>, 1: int}>
     */
    public static function coverageBeforeFlipProvider(): iterable
    {
        for ($seed = 1; $seed <= 25; $seed++) {
            $files = self::generateFileSet($seed, true);

            // Extra pre-existing objects in the bucket (additive, deterministic).
            mt_srand($seed * 7919);
            $extra = mt_rand(0, 5);

            yield "coverage-seed-{$seed}" => [$files, $extra];
        }

        // Explicit boundary: empty local set (nothing to migrate) — drift 0.
        yield 'coverage-empty-local' => [[], 0];

        // Explicit boundary: only *.tmp files => effective local count 0.
        yield 'coverage-only-tmp' => [['a.tmp', 'sub/b.TMP', 'x/y/c.tmp'], 3];
    }

    /**
     * Arbitrary local file sets with an incomplete sync (bucket missing some
     * objects). Deterministic across runs via per-case seeds.
     *
     * @return iterable<string, array{0: list<string>, 1: int}>
     */
    public static function partialSyncProvider(): iterable
    {
        $count = 0;

        for ($seed = 101; $seed <= 160 && $count < 25; $seed++) {
            $files          = self::generateFileSet($seed, true);
            $effectiveLocal = 0;
            foreach ($files as $f) {
                if (strtolower(pathinfo($f, PATHINFO_EXTENSION)) !== 'tmp') {
                    $effectiveLocal++;
                }
            }

            if ($effectiveLocal < 1) {
                continue; // need at least one file to be missing
            }

            mt_srand($seed * 104729);
            $missing = mt_rand(1, $effectiveLocal);

            $count++;
            yield "partial-seed-{$seed}" => [$files, $missing];
        }
    }

    // ── Helpers ─────────────────────────────────────────────────────────────

    /**
     * Deterministically generate a set of relative local file paths for a seed.
     * Some files are placed in nested category/id subdirectories and some carry
     * a `*.tmp` extension (which the command must exclude from the count).
     *
     * @return list<string>
     */
    private static function generateFileSet(int $seed, bool $forceNonTmp): array
    {
        mt_srand($seed);

        $numFiles   = mt_rand(1, 12);
        $categories = ['pago_gestor', 'ine', 'comprobante', 'contrato', 'foto'];
        $exts       = ['jpg', 'png', 'pdf', 'tmp', 'jpeg', 'tmp'];

        $files      = [];
        $hasNonTmp  = false;

        for ($i = 0; $i < $numFiles; $i++) {
            $ext  = $exts[mt_rand(0, count($exts) - 1)];
            $name = 'file' . $seed . '_' . $i . '_' . mt_rand(1000, 9999) . '.' . $ext;

            // ~60% of files live in a nested <category>/<id>/ path.
            if (mt_rand(0, 9) < 6) {
                $cat  = $categories[mt_rand(0, count($categories) - 1)];
                $id   = (string) mt_rand(1, 99999);
                $path = $cat . '/' . $id . '/' . $name;
            } else {
                $path = $name;
            }

            if (strtolower($ext) !== 'tmp') {
                $hasNonTmp = true;
            }

            $files[] = $path;
        }

        // Ensure at least one countable (non-tmp) file exists for the property
        // to be meaningful when requested.
        if ($forceNonTmp && !$hasNonTmp) {
            $files[] = 'guaranteed_' . $seed . '.jpg';
        }

        return $files;
    }

    /**
     * Number of files that the command counts (everything except `*.tmp`,
     * case-insensitive), mirroring S3MigrateCheck::countLocalFiles().
     *
     * @param list<string> $files
     */
    private function effectiveLocalCount(array $files): int
    {
        $count = 0;
        foreach ($files as $f) {
            if (strtolower(pathinfo($f, PATHINFO_EXTENSION)) !== 'tmp') {
                $count++;
            }
        }

        return $count;
    }

    /**
     * Create a fresh temp uploads root and materialize the given relative files.
     *
     * @param list<string> $files
     */
    private function seedLocalRoot(array $files): string
    {
        $root = sys_get_temp_dir() . '/s3migratecheck_' . bin2hex(random_bytes(6));
        if (!is_dir($root)) {
            mkdir($root, 0777, true);
        }
        $this->tempRoots[] = $root;

        foreach ($files as $rel) {
            $full = $root . '/' . $rel;
            $dir  = dirname($full);
            if (!is_dir($dir)) {
                mkdir($dir, 0777, true);
            }
            file_put_contents($full, 'x');
        }

        return $root;
    }

    /**
     * Build an S3MigrateCheck wired to a temp localRoot and to a MockHandler-backed
     * S3 client that reports exactly $s3Count objects (single ListObjectsV2 page).
     */
    private function makeCommand(string $root, int $s3Count): S3MigrateCheck
    {
        $config            = new FileStorageConfig();
        $config->localRoot = $root;
        $config->bucket    = 'test-bucket';
        $config->region    = 'us-east-1';

        $mock = new MockHandler();
        $mock->append(new Result([
            'KeyCount'    => $s3Count,
            'IsTruncated' => false,
            'Contents'    => [],
            '@metadata'   => ['statusCode' => 200],
        ]));

        $client = new S3Client([
            'version'     => 'latest',
            'region'      => 'us-east-1',
            'credentials' => ['key' => 'test', 'secret' => 'test'],
            'handler'     => $mock,
        ]);

        return (new S3MigrateCheck(Services::logger(), service('commands')))
            ->setConfig($config)
            ->setS3Client($client);
    }

    /**
     * Recursively remove a directory tree (temp cleanup only).
     */
    private function removeTree(string $path): void
    {
        if (!is_dir($path)) {
            if (is_file($path)) {
                @unlink($path);
            }

            return;
        }

        $items = scandir($path) ?: [];
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }
            $child = $path . '/' . $item;
            if (is_dir($child)) {
                $this->removeTree($child);
            } else {
                @unlink($child);
            }
        }
        @rmdir($path);
    }
}
